title: ASMR = Zvuky, ktoré možno cítiť
baseURL: https://amazing-kepler-3641a5.netlify.com/
languageCode: cs-cz
publishDir: public
googleAnalytics: "UA-139389898-1"

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archív
      identifier: post
      url: /post/
      weight: 20

params:
  description:
  authors: Alex, Gabika

